# Workflow to automate installation and unit testing of SedEdu on various python versions and operating systems

name: build

on: [push, pull_request]

jobs:
  test-conda:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.7, 3.8, 3.9]
    env:
      OS: ${{ matrix.os }}
      PYTHON: ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          channels: conda-forge
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        shell: bash -l {0}
        run: |
          conda install --name test --file requirements.txt
          pip install pytest pytest-mpl pytest-qt pytest-cov coveralls
      - name: Conda info
        shell: bash -l {0}
        run: |
          conda info
          conda list
      - name: Install SedEdu
        shell: bash -l {0}
        run: |
          pip install -e .
      - name: Test with pytest
        shell: bash -l {0}
        run: |
          pytest --ignore=sededu/modules/ --ignore-glob='*gui.py' --cov=sededu/ --cov-report=xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          env_vars: OS,PYTHON
          name: codecov-umbrella
          fail_ci_if_error: true
